on:
  push:
    branches:
      - main
      - 'GH-Pages'
  pull_request:
    branches:
      - main
      - 'GH-Pages'

name: Clean-Up

jobs:
  jekyll-build:
    name: (re)Build Jekyll site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jekyll-version: [3.9, 4.3]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Not needed with a .ruby-version file
        bundler-cache: false
    - name: Bundle The Install
      run: bundle install
    - name: Install Jekyll ${{ matrix.jekyll-version }}
      run: gem install jekyll -v ${{ matrix.jekyll-version }}
    - name: Update Search
      run: bundle exec rake search:init
    - name: Build Site
      run: bundle exec jekyll build

  assets:
    name: Confirm CSS and JS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
